services:
  - name: "<%= project_name %>-web"
    container_port: 3000
    service_type: "web_service"
environment_variables:
  - name: "DATABASE_URL"
    value: "redis://redis.<%= cluster_name %>.svc.local/<%= number %>"
  - name: "BRANCH"
    value: "<%= branch_name %>"
  - name: "USER"
    value: "<%= username %>"
scripts:
  predeploy: echo "Pre create command"
  postdeploy: echo "Post create command"
  predestroy: echo "Pre destroy command"
  postdestroy: echo "Post destroy command"